version: 2.1
jobs:
  build:
    machine:
      image: android:202102-01
    resource_class: large
    environment:
      JVM_OPTS: -Xmx4096m
      JAVA_OPTS: -Xmx4096m
      GRADLE_OPTS: -Xmx4096m
    steps:
      - checkout
      - run:
          name: test
          command: gradle build --info
workflows:
  build:
    jobs:
      - build
