version: 2.1
jobs:
  build:
    machine:
      image: android:202102-01
    resource_class: large
    environment:
      JVM_OPTS: -Xmx4096m
    steps:
      - checkout
      - run:
          name: aa
          command: |
            aa=test
      - run:
          name: bb
          command: |
            echo $aa
workflows:
  build:
    jobs:
      - build
