version: 2.1
jobs:
  build:
    machine:
      image: android:202102-01
    resource_class: large
    environment:
      JVM_OPTS: -Xmx4096m
    steps:
      - checkout
      -run:
        name: a
        command: |
          aa="test"
      -run:
        name: b
        command: |
          echo $aa
workflows:
  build:
    jobs:
      - build
