version: 2.1
jobs:
  build:
    machine:
      image: android:202102-01
    resource_class: large
    environment:
      JAVA_OPTS: -Xmx4096m
    steps:
      - checkout
      - run:
          name: aa
          command: gradle -v
workflows:
  build:
    jobs:
      - build
