version: 2.1
jobs:
  build:
    machine:
      image: android:202102-01
    resource_class: large
    environment:
      JAVA_OPTS: -Xmx4096m
      JVM_OPTS: -Xmx4097
    steps:
      - checkout
      - run:
          name: aa
          command: ls -la /opt/*
workflows:
  build:
    jobs:
      - build
