version: 2.1
jobs:
  build:
    machine:
      image: android:202102-01
    resource_class: large
    #environment:
      #JAVA_OPTS: -Xmx4096m
    steps:
      - checkout
      - run:
          name: aa
          command: echo JAVA_OPTS
workflows:
  build:
    jobs:
      - build
